# Project information
site_name: MAGELLAN
site_description: 'MAGELLAN Dokumentation'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.magellan.stueber.de'

# Copyright
copyright: © 2021 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.magellan7.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    features:
        - navigation.tabs
        - navigation.instant
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Impressum
      link: https://www.stueber.de/imprint.php
    - label: Datenschutz
      link: https://legal.stueber.de/privacy.php

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    - img2fig

# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
- Allgemein: 
    - Einführung: index.md
    - Was ist neu?: changelog/changelog.md
    - Neuerungen MAGELLAN 9: changelog/neu.mag9.md
    - Archiv:
        - Neuerungen MAGELLAN 8: changelog/neu.mag8.md
        - Neuerungen MAGELLAN 7: changelog/neu.mag7.md
        - Änderungen 2021: changelog/changelog2021.md
        - Änderungen 2020: changelog/changelog2020.md
        - Änderungen 2019: changelog/changelog2019.md
- Schulverwaltung:
    - Übersicht: schulverwaltung/schulverwaltung.md
    - Installation: 
      - Übersicht: schulverwaltung/installation/README.md
      - Systemvoraussetzungen: schulverwaltung/installation/systemvoraussetzungen.md
      - Server/Einzelplatz installieren: schulverwaltung/installation/version9/server.installieren.md
      - Arbeitsplatz installieren: schulverwaltung/installation/version9/arbeitsplatz.installieren.md
      - Lizenzieren: schulverwaltung/installation/lizenzieren.md
      - Die Pathsdatei: schulverwaltung/installation/die-pathsdatei.md
      - Terminalserver: schulverwaltung/installation/terminalserver.md
      - Mehrere Schulen auf einem Server: schulverwaltung/installation/struktur.md
      - Probleme bei der Installation?: schulverwaltung/update/probleme.md
      - Archiv:
        - V8 Server/Einzelplatz installieren: schulverwaltung/installation/version8/server.installieren.md
        - V8 Arbeitsplatz installieren: schulverwaltung/installation/version8/arbeitsplatz.installieren.md
        - V7 Server/Einzelplatz installieren: schulverwaltung/installation/version7/server.installieren.md
        - V7 Arbeitsplatz installieren: schulverwaltung/installation/version7/arbeitsplatz.installieren.md
    - Upgrade:
      - von 8 auf 9: schulverwaltung/upgrade/umstieg-von-8-auf-9.md
      - von 7 auf 9: schulverwaltung/upgrade/umstieg-von-7-auf-9.md
      - von 6 auf 9: schulverwaltung/upgrade/umstieg-von-6-auf-9.md
      - Archiv:
        - von 7 auf 8: schulverwaltung/upgrade/umstieg-von-7-auf-8.md
        - von 6 auf 8: schulverwaltung/upgrade/umstieg-von-6-auf-8.md
        - von 6 auf 7: schulverwaltung/upgrade/umstieg-von-6-auf-7.md
        - Eigene Berichte anpassen: schulverwaltung/upgrade/berichte_anpassen.md   
    - Update: 
      - Übersicht: schulverwaltung/update/README.md
      - Vorbereitung: schulverwaltung/update/vorbereitung.md
      - Updates verteilen: schulverwaltung/update/wie-kann-ein-update-verteilt-werden.md
      - Firebird aktualisieren: schulverwaltung/update/firebird-aktualisieren.md
      - Probleme beim Update?: schulverwaltung/update/probleme.md
    - So gehen Sie vor: 
      - Übersicht: schulverwaltung/howto/README.md
      - Datenbank vorbereiten: schulverwaltung/howto/preparation.md
      - Lehrer: schulverwaltung/howto/lehrer.md
      - Klassen: schulverwaltung/howto/classes.md
      - Bewerber: schulverwaltung/howto/bewerber.md
      - Schüler: schulverwaltung/howto/schueler.md
      - Sorgeberechtigte: schulverwaltung/howto/sorgeberechtigte.md
      - Betriebe und Schulen: schulverwaltung/howto/betriebe.schulen.md
      - Personen und Adressen: schulverwaltung/howto/personen.md
      - Sortieren, Gruppieren, Filtern, Suchen: schulverwaltung/howto/sort-group-filter-search.md
      - Merkmalsfelder: schulverwaltung/howto/merkmalsfelder.md
      - Halbjahreswechsel: schulverwaltung/howto/halbjahreswechsel.md
      - Schuljahreswechsel: schulverwaltung/howto/schuljahreswechsel.md
      - Sonderfälle in der Schullaufbahn: schulverwaltung/howto/sonderfaelle.md
      - Zeugnisdaten: 
        - Fachdaten: schulverwaltung/howto/zeugnisdaten1.md
        - Leistungsdaten: schulverwaltung/howto/zeugnisdaten2.md
        - Weiter Zeugnisdaten: schulverwaltung/howto/zeugnisdaten3.md
      - ENBREA Leistungen: schulverwaltung/howto/enbrea.leistungen.md
      - Prüfungsnummer generieren: schulverwaltung/howto/pruefungsnummer.md
      - Durchschnitt/Abschluss berechnen: schulverwaltung/howto/durchschnitt-abschluss.md
      - Gymnasiale Oberstufe: 
        - Übersicht: schulverwaltung/howto/Oberstufe/gymnasium.md 
        - Vorbereitung: schulverwaltung/howto/Oberstufe/vorbereitung.md
        - Schüler synchronisieren: schulverwaltung/howto/Oberstufe/sync.md
        - Fachwahl: schulverwaltung/howto/Oberstufe/fachwahl.md
        - Abiturberechnung: schulverwaltung/howto/Oberstufe/abiturberechnung.md
      - Berufsschulmatrix: schulverwaltung/howto/berufsschulmatrix.md
      - Formulare, Listen und Zeugnisse: schulverwaltung/howto/berichte.md
      - Anleitungen zu Berichten: schulverwaltung/howto/berichte-verz.md
      - Seriendruck und Serienmail: schulverwaltung/howto/seriendruck.md
      - Dokumentenverwaltung/Export: schulverwaltung/howto/dokumentenverwaltung_export.md
      - Kurznachrichten: schulverwaltung/howto/kurznachrichten.md
      - Stundenplandaten: schulverwaltung/howto/stundenplaene.md
      - Abgleich DAVINCI und MAGELLAN: schulverwaltung/howto/abgleich_mit_dav.md
    - Administration: 
      - Übersicht: schulverwaltung/admin/administration.md
      - MAGELLAN ADMINISTRATOR: 
        - Übersicht: schulverwaltung/admin/magellan.administrator.md
        - Datenbankverbindungen: schulverwaltung/admin/admin.datenbankverbindungen.md
        - Datenbanksicherungen: schulverwaltung/admin/sicherung.md
        - Benutzerverwaltung: schulverwaltung/admin/users.md
        - MyMAGELLAN Center: schulverwaltung/admin/mymagellan-center.md
        - Datenbankpflege: schulverwaltung/admin/datenbankpflege8.md
        - Datenaustausch: schulverwaltung/admin/datenaustausch.md
        - Logbuch: schulverwaltung/admin/logbuch.md
      - Weitere Themen: 
        - Übersicht: schulverwaltung/admin/weitere.themen.md
        - Optionen: schulverwaltung/admin/preferences.md
        - Sicherung per Windows Task: schulverwaltung/admin/sicherung.windows.task.md
        - Mehrmandantenlösung: schulverwaltung/admin/mehrmandantenloesung.md
        - Access-Anbindung: schulverwaltung/admin/access.anbindung.md
        - Protokollierung: schulverwaltung/admin/protocol.md
        - Aktionen im Silentmode: schulverwaltung/installation/magellan-administrator-im-silentmode-starten.md
        - MAGELLAN Scripting: https://doc.magellan-scripting.stueber.de
    - Referenz: 
      - Übersicht: schulverwaltung/reference/README.md
      - Tastaturkürzel: schulverwaltung/reference/shortcuts.md
      - Schlüsselverzeichnisse: schulverwaltung/reference/catalogs.md
      - keys-Dateien: schulverwaltung/reference/keys-dateien.md
      - Seriendruckfelder: schulverwaltung/reference/seriendruckfelder.md
      - Vorlagenfelder: schulverwaltung/reference/vorlagenfelder.md
    - Regionales: 
      - Übersicht: schulverwaltung/regionales/README.md
      - Ausland:
        - Oberstufe: schulverwaltung/regionales/ausland/oberstufe.md
      - Berlin: 
        - Übersicht: schulverwaltung/regionales/berlin/berlin.md
        - Berliner Felder: schulverwaltung/regionales/berlin/felder.md
        - Skriptüberblick: schulverwaltung/regionales/berlin/skriptuebersicht.md
        - Angaben für die Oberstufe: 
          - Übersicht: schulverwaltung/regionales/berlin/oberstufe.md
          - BER-APO-2017: schulverwaltung/regionales/berlin/oberstufe/ber-apo-2017.md
          - BER-FW-APO-2017: schulverwaltung/regionales/berlin/oberstufe/ber-fw-apo-2017.md
          - BER-APO-KO-2017: schulverwaltung/regionales/berlin/oberstufe/ber-apo-ko-2017.md
          - BER-FW-APO-BBS-2011: schulverwaltung/regionales/berlin/oberstufe/ber-fw-apo-bbs-2011.md
          - BER-APO-2011: schulverwaltung/regionales/berlin/oberstufe/ber-apo-2011-und-ber-fw-apo-2011.md
          - BER-FW-APO-2011: schulverwaltung/regionales/berlin/oberstufe/ber-fw-apo-2011.md
          - BER-APO-KO-2011: schulverwaltung/regionales/berlin/oberstufe/ber-apo-ko-2011.md
        - Schülerfachwahlen eingeben und prüfen: schulverwaltung/regionales/berlin/fachwahl.md
        - Schülerfachwahlen nach Untis übertragen: schulverwaltung/regionales/berlin/nach.untis.md
        - Schüler-Kurswahlen von Untis übernehmen: schulverwaltung/regionales/berlin/von.untis.md
        - Das Abitur: schulverwaltung/regionales/berlin/abitur.md
        - Die Fachhochschulreife: schulverwaltung/regionales/berlin/fhs.md
        - Berufsschulnoten: schulverwaltung/regionales/berlin/bs.md
        - Die Fachoberschule: 
          - Übersicht: schulverwaltung/regionales/berlin/fos.md
          - BER-APO-FOS-2006/2013: schulverwaltung/regionales/berlin/fos/ber-apo-fos-20062013.md
        - Statistik: schulverwaltung/regionales/berlin/statistik.md
      - Nordrhein-Westfalen: 
        - Abgleich mit SchülerOnline: schulverwaltung/regionales/nrw/schueleronline.md
      - Saarland: 
        - Lernfelder importieren: schulverwaltung/regionales/saarland/lernfelder-importieren.md
        - Zeugnisse mit Lernfeldern: schulverwaltung/regionales/saarland/zeugnisse.md
      - Sachsen: 
        - SAXSVS: schulverwaltung/regionales/sachsen/sachsen.md
    - Knowledge Base (FAQ): https://doc.kb.stueber.de/
- MyMAGELLAN Center: 
    - Einführung: mymagellancenter/einfuehrung.md
    - Verteilen: mymagellancenter/verteilen.md    
    - Organisation: mymagellancenter/organisation.md
    - Importlogik: mymagellancenter/importlogik.md
    - Einsammeln: mymagellancenter/einsammeln.md
- Bibliotheksverwaltung:
    - Überblick: bibliothek/index.md
    - Installation und Updates: bibliothek/installation/installation_und_updates.md
    - Optionen: bibliothek/installation/optionen.md 
    - So gehen Sie vor: 
        - Vorbereitung: bibliothek/howto/vorbereitung.md
        - Ausleiher: bibliothek/howto/ausleiher.md
        - Schüler: bibliothek/howto/schueler.md
        - Lehrer: bibliothek/howto/lehrer.md
        - Personen: bibliothek/howto/personen.md
        - Mandanten: bibliothek/howto/mandanten.md
        - Bücher / Medien: bibliothek/howto/buecher_medien.md
        - Verlage: bibliothek/howto/verlage.md
        - Lieferanten: bibliothek/howto/lieferanten.md
        - Medienkataloge: bibliothek/howto/katalog.md
        - Ausleihe: bibliothek/howto/ausleihe.md
        - Vorgänge: bibliothek/howto/vorgaenge.md
        - Mahnwesen: bibliothek/howto/mahnwesen.md
        - Effizient mit Listen/Tabellen arbeiten: bibliothek/howto/listen.md
        - Etiketten: bibliothek/howto/etiketten.md
        - Berichte und Vorlagen: bibliothek/howto/bericht_vorlage.md
        - Archivieren: bibliothek/howto/archivieren.md
        - Seriendruck: bibliothek/howto/seriendruck.md
        - Schlüsselverzeichnisse: bibliothek/howto/schluesselverzeichnisse.md




